#!/bin/bash

#THIS_DIR=${PWD}
PARENT_DIR=${PWD}
GRANDPARENT_DIR="$(dirname "$THIS_DIR")"
PUBLIC_DIR=${PARENT_DIR}
SH_DIR=${PARENT_DIR}/sh

WP_BASE_DIR=${PUBLIC_DIR}/wp
WP_BASE_CONTENT_DIR=${WP_BASE_DIR}/wp-content
WP_BASE_THEMES_DIR=${WP_BASE_CONTENT_DIR}/themes
WP_CONTENT_DIR=${PUBLIC_DIR}/wp-content
WP_THEMES_DIR=${WP_CONTENT_DIR}/themes
WP_UL_DIR=${WP_CONTENT_DIR}/uploads
WP_CONFIG_FILE=${WP_BASE_DIR}/wp-config.php